### ISSUE TITLE
Multi-line single message is sent as multiple messages

### ISSUE THREAD

**Issue by MagicFormula** [cshtdd/aws-cloudwatch-forwarder#1]
Hey,
great strait-forward library - you've got my star :)

I have an issue with the fact that every multi-line single message is sent as multiple messages.
For example, if I run the following line:
`console.log("object =\n" + JSON.stringify({a:"b"}, null, 2));`
I get 4 different event to my CloudWatch:
`object =`
followed by
`{`
followed by
`"a"="b"`
followed by
`}`

Is there a way to fix that?

**Comment by MagicFormula** [comment]
I'm using node.js/express.js on Heroku, and I see Heroku's logs doing the same - so it might be their problem. Still, do you know how to solve it?

**Comment by cshtdd** [comment]
I can think of the following two options.

`Option 1`: Escape new line characters before logging them out.

`Option 2`: Create a setting in the library to do that automatically.

I recommend sticking to `Option 1` for now

**Comment by Asaf-S** [comment]
Hey @cshtdd, first of all - thank you for your response, this is still a big issue for me (sorry I'm answering so late, I must have missed GitHub's email)... 

I understood from [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html) that AWS CloudWatch does support multiline messages:
> The default value is ‘^[^\s]' so any line that begins with non-whitespace character closes the previous log message and starts a new log message.

So I've tried replacing every '\n' with '\n\t' (or space), but it still doesn't work.
There's just an extra tab between the timestamp and the log message.

Is it possible that you're adding your own prefix, so that the first character isn't whitespace?
I've tried forking your code, but failed to fix this...

**Comment by Asaf-S** [comment]
Or maybe you could allow editing the Agent Configuration file, so that `multi_line_start_pattern` could be manually changed (saw it [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html))?

Although, this wouldn't solve the problem, as users need to guess your added prefix...

**Comment by cshtdd** [comment]
Take a look at how this works. It subscribes to each line in the stdout/stderr of the child process.

https://github.com/cshtdd/aws-cloudwatch-forwarder/blob/master/lib/inputRepository.js

https://github.com/cshtdd/aws-cloudwatch-forwarder/blob/master/lib/streamLinesSubscriber.js

Even when CloudWatch supports multiline inputs this library is splitting the stdout/stderr. And sending each line as a separate message.

It would be hard to know what constitutes a single CloudWatch message otherwise.

I don’t have time to work on enhancements on this project. It has good test coverage so feel free to add the functionality you need to your fork.
